polla/config/routes.rb
Polla::Application.routes.draw do
  resources :partidos

  resources :users

  

end

polla/app/models/partido.rb
class Partido < ActiveRecord::Base
end

polla/app/models/user.rb
class User < ActiveRecord::Base
	
end

polla/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

polla/app/controllers/partidos_controller.rb
class PartidosController < ApplicationController
  before_action :set_partido, only: [:show, :edit, :update, :destroy]

  # GET /partidos
  # GET /partidos.json
  def index
    @partidos = Partido.all
  end

  # GET /partidos/1
  # GET /partidos/1.json
  def show
  end

  # GET /partidos/new
  def new
    @partido = Partido.new
  end

  # GET /partidos/1/edit
  def edit
  end

  # POST /partidos
  # POST /partidos.json
  def create
    @partido = Partido.new(partido_params)

    respond_to do |format|
      if @partido.save
        format.html { redirect_to @partido, notice: 'Partido was successfully created.' }
        format.json { render action: 'show', status: :created, location: @partido }
      else
        format.html { render action: 'new' }
        format.json { render json: @partido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partidos/1
  # PATCH/PUT /partidos/1.json
  def update
    respond_to do |format|
      if @partido.update(partido_params)
        format.html { redirect_to @partido, notice: 'Partido was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @partido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partidos/1
  # DELETE /partidos/1.json
  def destroy
    @partido.destroy
    respond_to do |format|
      format.html { redirect_to partidos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partido
      @partido = Partido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partido_params
      params.require(:partido).permit(:equipo1, :equipo2, :res1, :res2)
    end
end

polla/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

polla/app/helpers/application_helper.rb
module ApplicationHelper
end

polla/app/helpers/partidos_helper.rb
module PartidosHelper
end

polla/app/helpers/users_helper.rb
module UsersHelper
end

polla/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Polla</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

polla/app/views/partidos/_form.html.erb
<%= form_for(@partido) do |f| %>
  <% if @partido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@partido.errors.count, "error") %> prohibited this partido from being saved:</h2>

      <ul>
      <% @partido.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :equipo1 %><br>
    <%= f.text_field :equipo1 %>
  </div>
  <div class="field">
    <%= f.label :equipo2 %><br>
    <%= f.text_field :equipo2 %>
  </div>
  <div class="field">
    <%= f.label :res1 %><br>
    <%= f.number_field :res1 %>
  </div>
  <div class="field">
    <%= f.label :res2 %><br>
    <%= f.number_field :res2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

polla/app/views/partidos/edit.html.erb
<h1>Editing partido</h1>

<%= render 'form' %>

<%= link_to 'Show', @partido %> |
<%= link_to 'Back', partidos_path %>

polla/app/views/partidos/index.html.erb
<h1>Listing partidos</h1>

<table>
  <thead>
    <tr>
      <th>Equipo1</th>
      <th>Equipo2</th>
      <th>Res1</th>
      <th>Res2</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @partidos.each do |partido| %>
      <tr>
        <td><%= partido.equipo1 %></td>
        <td><%= partido.equipo2 %></td>
        <td><%= partido.res1 %></td>
        <td><%= partido.res2 %></td>
        <td><%= link_to 'Show', partido %></td>
        <td><%= link_to 'Edit', edit_partido_path(partido) %></td>
        <td><%= link_to 'Destroy', partido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Partido', new_partido_path %>

polla/app/views/partidos/new.html.erb
<h1>New partido</h1>

<%= render 'form' %>

<%= link_to 'Back', partidos_path %>

polla/app/views/partidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Equipo1:</strong>
  <%= @partido.equipo1 %>
</p>

<p>
  <strong>Equipo2:</strong>
  <%= @partido.equipo2 %>
</p>

<p>
  <strong>Res1:</strong>
  <%= @partido.res1 %>
</p>

<p>
  <strong>Res2:</strong>
  <%= @partido.res2 %>
</p>

<%= link_to 'Edit', edit_partido_path(@partido) %> |
<%= link_to 'Back', partidos_path %>

polla/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

polla/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

polla/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

polla/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

polla/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>